### ISSUE TITLE
Keyboard Notes

### ISSUE THREAD

**Issue by AtelesPaniscus** [exercism/gnu-apl#26]
If you use a machine that is running the X-11 Window system then you are fortunate because an APL keyboard definition should already be installed.  Check for _/usr/share/X11/xkb/symbols/apl_ (or equivalent).

You should be able to configure the APL keyboard as an alternative keyboard layout.  There are many desktops so the details differ.  Navigate to:

```
    System Setting → Hardware → Input Devices → Keyboard → Layouts
```

There click on the `Add` button of `Configure Layouts`.  By rights, APL will be at the top of the alphabetic list that pop-ups.

You may want to set the 'switching policy' to `Window` and to choose `shortcuts` for `switching layouts`.  Go to the 'Advanced' tab and expand the `Keys(s) to change layout` for a full list of available `shortcuts `.
 
A very effective choice is **both** `Left Win (while pressed)` and `Right Win (while pressed)`.  This allows you to enter APL symbols by modifier making use of two keys you may have never ever had any use for before.

If your desktop is too user friendly to offer you the APL keyboard you can edit a flat configuration file by hand and restart your X server instead.

On GNU/Linux Debian and derivatives, edit _/etc/default/keyboard_.  Two lines will need to be changed to something similar to:

```bash
XKBLAYOUT="us,apl"

XKBOPTIONS="compose:menu,grp:lwin_switch,grp:rwin_switch
```

**Comment by marnen** [comment]
Also, Dyalog has fonts and keyboard layouts available for free download for Mac, Windows, and Linux at https://www.dyalog.com/apl-font-keyboard.htm .

At some point I should try making an iOS APL keyboard layout. :)
