### ISSUE TITLE
Moving from Travis to GitHub Actions

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/gnu-apl#42]
Hello 🙂 

Over the last few months we've been transferring all our CI from Travis to [GitHub Actions (GHA)](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions). We've found that GHA are easier to work with, more reliable, and much much faster. 

Based on our success with GHA and increasing intermittent failures on Travis, we have now decided to try and remove Travis from Exercism's org altogether and [shift everything to GHA](https://github.com/exercism/exercism/issues/5396). This issue acts as a call to action if your track is still using Travis. 

For most CI checks this should be a transposing from Travis' syntax to [GHA syntax](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions), and hopefully quite straightforward (see [this PR for an example](https://github.com/exercism/csharp/pull/1338/files)).  However, if you do encounter any issues doing this, please ask on Slack where lots of us now have experience with GHA, or post a comment here and I'll tag relevant people. This would also make a good Hacktoberfest issue for anyone interested in making their first contribution 🙂 

If you've already switched this track to GHA, please feel free to close this issue and ignore it.

Thanks!

**Comment by ErikSchierboom** [comment]
Thanks to @SleeplessByte, we now have a really nice document and some starting workflows that you can use to help switch to GitHub Actions: https://github.com/exercism/problem-specifications/tree/master/workflows#workflow-templates

**Comment by marnen** [comment]
I'll see if this will work. CI was hard enough to get working for APL on Travis, so I don't relish trying to do it again on a different platform.

**Comment by SleeplessByte** [comment]
@marnen You can follow the [10 minute guide](https://github.com/exercism/problem-specifications/tree/master/workflows#migrating-from-travis) in the document Erik posted. 

I just looked at [your track's `.travis.yml`](https://github.com/exercism/gnu-apl/blob/master/.travis.yml). I can see the `language` used is `bash` which is resolved to [Travis: Minimal](https://docs.travis-ci.com/user/languages/minimal-and-generic/), which can be achieved using the [`ubuntu-latest`](https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources) image, skipping the "setup tools" step all-together.

You can copy the `env`.

The "steps" part would then become:

```
- <checkout>
- bin/install-apl
- docker run apl 'bin/run-all-tests'
```

Configlet linting is achieved by copying the `configlet` workflow. You don't need to change anything.

**Comment by marnen** [comment]
@SleeplessByte That might help; thanks. Will look at this in my copious spare time. :D
