### ISSUE TITLE
Add language blurb

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/gnu-apl#68]
The track's `config.json` file must have a non-empty `blurb` property. This property should contain a short description (less than or equal to 400 characters) of the language. See https://github.com/exercism/docs/blob/main/building/tracks/config-json.md.

## Tracking

https://github.com/exercism/v3-launch/issues/37

**Comment by Russtopia** [comment]
I included a language blurb in one of my PRs adding some gnu-apl exercise solutions. See PRs #81, PR #82, PR #83

**Comment by ErikSchierboom** [comment]
@Russtopia Great. One any of those PRs is merged, this can be closed.
